-- ============================================================
-- 0013_vehicle_detail_fields.sql
-- Closes the schema gap against the "My Cars" reference structure, and opens
-- a SAFE, column-scoped customer edit path on public.vehicles.
--
-- Run this AFTER 0012.
--
-- PARTIALLY APPLIED. As of 2026-08-21 the live project already has sections A,
-- B1 and C from an earlier run of this file; section B2 (the INSERT guard) and
-- the ref_no upgrade are new and are NOT applied. The whole file is safe to
-- re-run end to end -- every statement is `if not exists` / `or replace` /
-- `drop ... if exists` first -- so re-running it is the way to land B2 rather
-- than hand-picking statements out of it.
--
-- Jobs, in order:
--   A.  New columns on vehicles / profiles / vehicle_photos (data gap).
--   B1. A customer UPDATE policy on vehicles (currently admin-only), plus a
--       whitelist trigger that is the actual security boundary.
--   B2. A matching whitelist guard on INSERT, because a customer fills in
--       total_amount when ADDING a vehicle -- locking UPDATE alone would only
--       move the hole to the other statement.
--   C.  A customer DELETE policy on vehicle_photos, so "remove photo" works.
--
-- A rollback block sits at the bottom of this file.
--
-- Nothing here drops, renames or retypes an existing column. Every addition is
-- nullable (or defaulted), so existing rows stay valid and every read path that
-- does not know about these columns keeps working unchanged.
-- ============================================================


-- ============================================================
-- A. DATA GAP
-- ============================================================

-- ------------------------------------------------------------
-- A1. vehicles: a short human-facing number.
--
-- The reference table's first column is a small integer the customer can read
-- out over the phone. Our primary key is a uuid and stays the primary key --
-- this is a display number only, never a foreign key target.
--
-- Adding an identity column backfills existing rows in physical order, which
-- is fine: these numbers have no meaning beyond being short and unique.
--
-- GENERATED ALWAYS, not BY DEFAULT: with BY DEFAULT a client could supply its
-- own ref_no and Postgres would accept it. ALWAYS makes the server the only
-- source of this number, so the guard below does not have to police it -- the
-- column definition itself rejects a supplied value (SQLSTATE 428C9).
-- ------------------------------------------------------------
alter table public.vehicles
  add column if not exists ref_no bigint generated always as identity;

-- For a database where an EARLIER version of this file already created ref_no
-- as GENERATED BY DEFAULT: `add column if not exists` skips the column
-- entirely, so it would keep accepting a client-supplied value. This statement
-- upgrades it in place and is a no-op when the column is already ALWAYS.
alter table public.vehicles
  alter column ref_no set generated always;

create unique index if not exists vehicles_ref_no_key on public.vehicles (ref_no);

-- ------------------------------------------------------------
-- A2. vehicles: where the car physically is.
--
-- This is NOT vehicles.status and must not be conflated with it. status is the
-- shipping lifecycle ('At Auction' -> 'Delivered') and is guarded by
-- guard_vehicle_status. `location` is the reference filter bar's axis, with its
-- own vocabulary. Both are admin-controlled.
--
-- Stored values are English and are never translated (same rule as status).
-- ------------------------------------------------------------
alter table public.vehicles
  add column if not exists location text
    constraint vehicles_location_check
    check (location is null or location in
      ('Auction', 'Warehouse', 'Container', 'Parking', 'Out'));

create index if not exists vehicles_location_idx on public.vehicles (location);

-- ------------------------------------------------------------
-- A3. vehicles: money the reference shows that we do not hold.
--
-- Both are admin-controlled. `debt` is NOT stored: the reference's Debt column
-- is derived as total_amount - paid, and duplicating it into a column would let
-- the two drift apart. auction_penalty is genuinely separate money and does get
-- a column.
-- ------------------------------------------------------------
alter table public.vehicles
  add column if not exists auction_penalty numeric not null default 0,
  add column if not exists final_price     numeric;

-- ------------------------------------------------------------
-- A4. vehicles: auction facts (Details card 2).
-- ------------------------------------------------------------
alter table public.vehicles
  add column if not exists auction_date  date,
  add column if not exists auction_house text,
  add column if not exists auction_state text,
  add column if not exists auction_city  text;

-- ------------------------------------------------------------
-- A5. vehicles: transportation facts (Details card 3) and the table's
-- "Expected opening date".
--
-- container_number and shipping_line already exist (0001) and are reused:
-- shipping_line is the reference's "Sea Line". No new column for either.
-- ------------------------------------------------------------
alter table public.vehicles
  add column if not exists loading_port            text,
  add column if not exists carrier                 text,
  add column if not exists terminal                text,
  add column if not exists auction_pickup_date     date,
  add column if not exists warehouse_delivery_date date,
  add column if not exists departure_date          date,
  add column if not exists entry_date              date,
  add column if not exists open_date               date,
  add column if not exists release_date            date,
  add column if not exists expected_opening_date   date;

-- ------------------------------------------------------------
-- A6. profiles: the Details panel's "Personal number".
--
-- Personal identification number. It sits on profiles, not vehicles, and is
-- already covered by the existing profiles_select policy: a customer reads only
-- their own row, admins read all. No new exposure.
--
-- It is NOT added to the customer-writable set below, because it is identity
-- data our staff verify. Admins set it.
-- ------------------------------------------------------------
alter table public.profiles
  add column if not exists personal_number text;

-- ------------------------------------------------------------
-- A7. vehicle_photos: the gallery category.
--
-- The reference gallery has four fixed columns. Photos a customer uploads are
-- auction photos, so that is the default; staff re-file them afterwards.
-- Stored values are lowercase English keys, translated only at render time.
-- ------------------------------------------------------------
alter table public.vehicle_photos
  add column if not exists category text not null default 'auction'
    constraint vehicle_photos_category_check
    check (category in ('auction', 'stock', 'driver', 'poti'));

create index if not exists vehicle_photos_category_idx
  on public.vehicle_photos (vehicle_id, category);


-- ============================================================
-- B. CUSTOMER EDIT PATH ON vehicles
--
-- Today vehicles_update (0003) is admin-only, so a customer cannot change a
-- vehicle at all -- there is no open hole to close, and nothing below weakens
-- anything that exists today. What follows OPENS a narrow hole deliberately and
-- fences it.
--
-- WHY A TRIGGER AND NOT A COLUMN GRANT: Postgres column-level UPDATE privileges
-- are granted per role, and admins are also members of `authenticated`.
-- Revoking table-wide UPDATE from `authenticated` to hand back a column list
-- would strip admins of the ability to write status, paid and total_amount.
-- A trigger can branch on is_admin(); a GRANT cannot. This is the same pattern
-- 0003 already uses for profiles.role / profiles.balance.
-- ============================================================

-- Lets a customer update a vehicle they own, and admins any vehicle.
-- WHICH COLUMNS a customer may touch is decided by the trigger below, not here:
-- a policy's WITH CHECK cannot see the OLD row, so it cannot express "this
-- column did not change".
drop policy if exists vehicles_update on public.vehicles;
create policy vehicles_update
  on public.vehicles
  for update
  to authenticated
  using (user_id = auth.uid() or public.is_admin())
  with check (user_id = auth.uid() or public.is_admin());

-- The security boundary for customer edits.
--
-- WHITELIST, not blacklist: every column is admin-only unless it is named in
-- CUSTOMER_EDITABLE below. A column added by a future migration is therefore
-- locked by default -- forgetting to think about it fails closed.
--
-- Deliberately NOT customer-editable, even though the Add Vehicle form collects
-- it: total_amount. Debt is total_amount - paid, so letting a customer rewrite
-- total_amount after the fact is letting them rewrite their own debt.
create or replace function public.guard_customer_vehicle_columns()
returns trigger
language plpgsql
security invoker              -- invoker: is_admin() must see the CALLER (see 0006)
set search_path = public, pg_temp
as $$
declare
  customer_editable constant text[] := array[
    'year', 'make', 'model', 'vin', 'lot_number',
    'container_number', 'booking_number', 'receiver',
    'shipping_line', 'notes'
  ];
  changed text;
begin
  if coalesce(public.is_admin(), false) then
    return new;
  end if;

  -- Diff OLD against NEW as jsonb so the check covers every column that exists
  -- now or later, without this function having to list them.
  for changed in
    select key
      from jsonb_each(to_jsonb(old)) as o(key, value)
      join jsonb_each(to_jsonb(new)) as n(key, value) using (key)
     where o.value is distinct from n.value
  loop
    if not (changed = any (customer_editable)) then
      raise exception 'Only an admin can change vehicles.%', changed
        using errcode = '42501';
    end if;
  end loop;

  return new;
end;
$$;

-- Both names are dropped so this file can be re-run against a database where an
-- earlier version of it already landed. CREATE TRIGGER has no OR REPLACE that
-- is safe on every Postgres this project might meet.
drop trigger if exists trg_guard_customer_vehicle_columns on public.vehicles;
drop trigger if exists a_guard_customer_vehicle_columns on public.vehicles;

-- Name starts with "a_" so it fires before trg_guard_vehicle_status: Postgres
-- runs BEFORE triggers in name order, and the clearer message should win.
-- The status guard from 0005/0006 stays in place regardless -- two independent
-- rejections of the same attack is the point, not redundancy to be tidied away.
create trigger a_guard_customer_vehicle_columns
  before update on public.vehicles
  for each row
  execute function public.guard_customer_vehicle_columns();


-- ------------------------------------------------------------
-- B2. THE INSERT SIDE.
--
-- Locking UPDATE alone only moves the hole: a customer fills total_amount in on
-- the Add Vehicle form, so they could file a car with total_amount = 0 and show
-- themselves no debt. There has never been a BEFORE INSERT trigger on this
-- table -- the only INSERT control is the vehicles_insert policy from 0003,
-- which checks user_id and status and nothing else.
--
-- An UPDATE guard can diff OLD against NEW. An INSERT has no OLD, and a column
-- the client omitted is indistinguishable from one it sent with the same value:
-- Postgres applies column defaults BEFORE row triggers fire. So this guard does
-- not try to detect what was "supplied" -- it REBUILDS the row from the table's
-- own defaults and copies back only the whitelisted columns.
--
-- IGNORE, NOT REJECT. A non-admin insert that carries an admin-owned column
-- succeeds; the value simply does not survive. See the report for the full
-- reasoning -- the short version is that the security outcome is identical
-- (the value never lands) while a hard reject would break every customer whose
-- browser still runs a cached bundle that sends the old field.
-- ------------------------------------------------------------

-- One row of this table's real column defaults, as jsonb.
--
-- Read out of the catalogue rather than hard-coded, so a column added by a
-- future migration is covered the moment it exists. Identity and generated
-- columns are skipped deliberately: they have no pg_attrdef row and the server
-- has already assigned them by the time the trigger runs, so overwriting them
-- with NULL would break the insert.
create or replace function public.vehicles_column_defaults()
returns jsonb
language plpgsql
-- VOLATILE, and it matters: the defaults it evaluates include gen_random_uuid()
-- and now(). Marked STABLE, a no-argument function is something the planner is
-- free to fold to a constant, which in a multi-row INSERT would hand every row
-- the SAME id and trip the primary key.
volatile
security invoker
set search_path = public, pg_temp
as $$
declare
  select_list text;
  result      jsonb;
begin
  select string_agg(
           coalesce(
             pg_get_expr(d.adbin, d.adrelid),
             'null::' || format_type(a.atttypid, a.atttypmod)
           ) || ' as ' || quote_ident(a.attname),
           ', ' order by a.attnum
         )
    into select_list
    from pg_attribute a
    left join pg_attrdef d
      on d.adrelid = a.attrelid
     and d.adnum   = a.attnum
   where a.attrelid = 'public.vehicles'::regclass
     and a.attnum > 0
     and not a.attisdropped
     and a.attidentity  = ''   -- ref_no: assigned by the sequence
     and a.attgenerated = '';  -- no generated columns today; closed anyway

  execute format('select to_jsonb(t) from (select %s) t', select_list)
     into result;

  return result;
end;
$$;

revoke execute on function public.vehicles_column_defaults() from public, anon;
grant execute on function public.vehicles_column_defaults() to authenticated;

-- The security boundary for customer inserts.
--
-- Same WHITELIST rule as the UPDATE guard, and deliberately the same list: what
-- a customer may type into the Add Vehicle form is exactly what they may later
-- correct. A column added by a future migration is not on the list, so it is
-- reset to its default -- closed by default, with no edit to this function.
create or replace function public.guard_customer_vehicle_insert()
returns trigger
language plpgsql
security invoker              -- invoker: is_admin() must see the CALLER (see 0006)
set search_path = public, pg_temp
as $$
declare
  customer_settable constant text[] := array[
    'year', 'make', 'model', 'vin', 'lot_number',
    'container_number', 'booking_number', 'receiver',
    'shipping_line', 'notes'
  ];
  supplied jsonb;
begin
  if coalesce(public.is_admin(), false) then
    return new;
  end if;

  select coalesce(jsonb_object_agg(key, value), '{}'::jsonb)
    into supplied
    from jsonb_each(to_jsonb(new))
   where key = any (customer_settable);

  /*
    Defaults first, then the whitelist on top, then identity last.

    user_id is NOT on the whitelist and is NOT reset to its default (NULL):
    resetting it would fail the vehicles_insert policy's user_id = auth.uid()
    check and no customer could add a car at all. Forcing it to auth.uid() is
    the same guarantee stated positively -- the row is filed under the caller,
    whatever the request asked for.

    created_at comes from the defaults, so a customer cannot backdate a vehicle
    either. That is not on the brief, but it falls out of the whitelist for
    free, which is the point of a whitelist.
  */
  new := jsonb_populate_record(
           new,
           public.vehicles_column_defaults()
             || supplied
             || jsonb_build_object('user_id', auth.uid())
         );

  return new;
end;
$$;

drop trigger if exists trg_guard_customer_vehicle_insert on public.vehicles;
drop trigger if exists a_guard_customer_vehicle_insert on public.vehicles;

create trigger a_guard_customer_vehicle_insert
  before insert on public.vehicles
  for each row
  execute function public.guard_customer_vehicle_insert();

-- NOTE on ordering: BEFORE ROW triggers run before the RLS WITH CHECK clause is
-- evaluated, so vehicles_insert (0003) sees the row this trigger produced --
-- user_id already forced to auth.uid() and status already reset to 'At Auction'.
-- That policy therefore stays exactly as 0003 wrote it and is now belt and
-- braces rather than the only control.


-- ============================================================
-- C. PHOTO REMOVAL
--
-- vehicle_photos INSERT already allows a customer to attach a photo to their
-- own vehicle (0003). DELETE was admin-only, so "remove this photo" had no
-- database path. This grants exactly the mirror of the INSERT policy.
--
-- The storage object itself is already deletable by its owner: the
-- vehicle_photos_object_delete policy (0008) keys on the <uid>/ path prefix.
-- ============================================================

drop policy if exists vehicle_photos_delete on public.vehicle_photos;
create policy vehicle_photos_delete
  on public.vehicle_photos
  for delete
  to authenticated
  using (
    public.is_admin()
    or exists (
      select 1 from public.vehicles v
      where v.id = vehicle_photos.vehicle_id
        and v.user_id = auth.uid()
    )
  );

-- vehicle_photos UPDATE stays admin-only: `category` is a staff filing
-- decision, and `url` is the storage path -- repointing it at another path is
-- exactly the move a customer should not have.


-- ============================================================
-- VERIFY
--
-- The real check is scripts/verify-admin.mjs, which runs all of this through
-- the anon key as a genuine customer session:  npm run verify:admin
--
-- By hand, as a NON-ADMIN customer -- each of these must FAIL:
--   update vehicles set status = 'Delivered'   where id = '<own vehicle>';
--   update vehicles set paid = 999999          where id = '<own vehicle>';
--   update vehicles set total_amount = 0       where id = '<own vehicle>';
--   update vehicles set auction_penalty = 0    where id = '<own vehicle>';
--   update vehicles set user_id = '<other>'    where id = '<own vehicle>';
--   update vehicles set vin = 'X'              where id = '<someone else''s>';
-- this must SUCCEED:
--   update vehicles set vin = 'TESTVIN', notes = 'ok' where id = '<own vehicle>';
-- and this must SUCCEED while storing total_amount = 0, status = 'At Auction':
--   insert into vehicles (user_id, make, total_amount, status)
--   values (auth.uid(), 'Probe', 99999, 'Delivered') returning *;
-- ============================================================


-- ============================================================
-- ROLLBACK
--
-- Everything 0013 did, undone, newest first. Paste the whole block to revert.
-- Section A's column drops are listed LAST because B and C depend on them.
--
-- WARNING: the `alter table ... drop column` statements below destroy any data
-- staff have already entered into those columns. Sections B and C alone (the
-- permission changes) can be reverted without touching the data -- stop before
-- the "-- A." heading if that is all you want.
-- ============================================================
--
-- -- C. photo removal: back to admin-only
-- drop policy if exists vehicle_photos_delete on public.vehicle_photos;
-- create policy vehicle_photos_delete
--   on public.vehicle_photos
--   for delete
--   to authenticated
--   using (public.is_admin());
--
-- -- B2. the insert guard
-- drop trigger if exists a_guard_customer_vehicle_insert on public.vehicles;
-- drop function if exists public.guard_customer_vehicle_insert();
-- drop function if exists public.vehicles_column_defaults();
-- -- only if you are stopping before the column drops below, which remove
-- -- ref_no outright:
-- alter table public.vehicles alter column ref_no set generated by default;
--
-- -- B1. the update guard, and the update policy back to admin-only (0003)
-- drop trigger if exists a_guard_customer_vehicle_columns on public.vehicles;
-- drop function if exists public.guard_customer_vehicle_columns();
-- drop policy if exists vehicles_update on public.vehicles;
-- create policy vehicles_update
--   on public.vehicles
--   for update
--   to authenticated
--   using (public.is_admin())
--   with check (public.is_admin());
--
-- -- A. the columns (DESTRUCTIVE -- see the warning above)
-- drop index if exists public.vehicle_photos_category_idx;
-- alter table public.vehicle_photos drop column if exists category;
-- alter table public.profiles       drop column if exists personal_number;
-- drop index if exists public.vehicles_location_idx;
-- drop index if exists public.vehicles_ref_no_key;
-- alter table public.vehicles
--   drop column if exists ref_no,
--   drop column if exists location,
--   drop column if exists auction_penalty,
--   drop column if exists final_price,
--   drop column if exists auction_date,
--   drop column if exists auction_house,
--   drop column if exists auction_state,
--   drop column if exists auction_city,
--   drop column if exists loading_port,
--   drop column if exists carrier,
--   drop column if exists terminal,
--   drop column if exists auction_pickup_date,
--   drop column if exists warehouse_delivery_date,
--   drop column if exists departure_date,
--   drop column if exists entry_date,
--   drop column if exists open_date,
--   drop column if exists release_date,
--   drop column if exists expected_opening_date;
--
-- -- 0005/0006's status guard is NOT touched by 0013 and must stay in place.
-- ============================================================